server:
  port: 8080

spring:
  application:
    name: ecommerce
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

endpoints:
  base: /api/v1

flyway:
  migrations: classpath:db/migrations